//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BinaryCalculationOperation.
const (
	BinaryCalculationOperationAdd      BinaryCalculationOperation = "add"
	BinaryCalculationOperationDivide   BinaryCalculationOperation = "divide"
	BinaryCalculationOperationMultiply BinaryCalculationOperation = "multiply"
	BinaryCalculationOperationPower    BinaryCalculationOperation = "power"
	BinaryCalculationOperationSubtract BinaryCalculationOperation = "subtract"
)

// Valid indicates whether the value is a known member of the BinaryCalculationOperation enum.
func (e BinaryCalculationOperation) Valid() bool {
	switch e {
	case BinaryCalculationOperationAdd:
		return true
	case BinaryCalculationOperationDivide:
		return true
	case BinaryCalculationOperationMultiply:
		return true
	case BinaryCalculationOperationPower:
		return true
	case BinaryCalculationOperationSubtract:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	DivisionByZero     ErrorCode = "division_by_zero"
	InternalError      ErrorCode = "internal_error"
	InvalidRequest     ErrorCode = "invalid_request"
	NegativeSquareRoot ErrorCode = "negative_square_root"
	ResultTooLarge     ErrorCode = "result_too_large"
	UndefinedResult    ErrorCode = "undefined_result"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case DivisionByZero:
		return true
	case InternalError:
		return true
	case InvalidRequest:
		return true
	case NegativeSquareRoot:
		return true
	case ResultTooLarge:
		return true
	case UndefinedResult:
		return true
	default:
		return false
	}
}

// Defines values for Operation.
const (
	OperationAdd        Operation = "add"
	OperationDivide     Operation = "divide"
	OperationMultiply   Operation = "multiply"
	OperationPercentage Operation = "percentage"
	OperationPower      Operation = "power"
	OperationSqrt       Operation = "sqrt"
	OperationSubtract   Operation = "subtract"
)

// Valid indicates whether the value is a known member of the Operation enum.
func (e Operation) Valid() bool {
	switch e {
	case OperationAdd:
		return true
	case OperationDivide:
		return true
	case OperationMultiply:
		return true
	case OperationPercentage:
		return true
	case OperationPower:
		return true
	case OperationSqrt:
		return true
	case OperationSubtract:
		return true
	default:
		return false
	}
}

// Defines values for PercentageCalculationOperation.
const (
	PercentageCalculationOperationPercentage PercentageCalculationOperation = "percentage"
)

// Valid indicates whether the value is a known member of the PercentageCalculationOperation enum.
func (e PercentageCalculationOperation) Valid() bool {
	switch e {
	case PercentageCalculationOperationPercentage:
		return true
	default:
		return false
	}
}

// Defines values for UnaryCalculationOperation.
const (
	UnaryCalculationOperationSqrt UnaryCalculationOperation = "sqrt"
)

// Valid indicates whether the value is a known member of the UnaryCalculationOperation enum.
func (e UnaryCalculationOperation) Valid() bool {
	switch e {
	case UnaryCalculationOperationSqrt:
		return true
	default:
		return false
	}
}

// BinaryCalculation An Operation over the Operands `left` and `right`.
type BinaryCalculation struct {
	// Left An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Left      Operand                    `json:"left"`
	Operation BinaryCalculationOperation `json:"operation"`

	// Right An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Right Operand `json:"right"`
}

// BinaryCalculationOperation defines model for BinaryCalculation.Operation.
type BinaryCalculationOperation string

// Calculation One Operation applied to its Operands, with the Result it produced. The Operands present are the ones the Operation's arity names. Session identity is not part of a Calculation.
type Calculation struct {
	// Exact Whether the Result carries its true mathematical value with no digits discarded. Always reported, never inferred.
	Exact bool `json:"exact"`

	// Left An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Left *Operand `json:"left,omitempty"`

	// Of An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Of *Operand `json:"of,omitempty"`

	// Operand An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Operand *Operand `json:"operand,omitempty"`

	// Operation The named arithmetic function a Calculation applies.
	Operation Operation `json:"operation"`

	// Percent An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Percent *Operand `json:"percent,omitempty"`

	// Result The Result in its shortest form that discards no digits.
	//
	// Example: 0.3
	Result string `json:"result"`

	// Right An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Right *Operand `json:"right,omitempty"`
}

// CalculationRequest A Calculation to perform. The variant is selected by `operation`, so an Operation can only be sent with the Operands its arity allows.
type CalculationRequest struct {
	union json.RawMessage
}

// Error defines model for Error.
type Error struct {
	// Error Machine-readable error code.
	Error ErrorCode `json:"error"`

	// Message Human-readable explanation, renderable without a code-to-copy map.
	//
	// Example: division by zero
	Message string `json:"message"`
}

// ErrorCode Machine-readable error code.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// History The Calculations a Session has performed, newest first.
type History = []Calculation

// Operand An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
//
// Example: 0.1
type Operand = string

// Operation The named arithmetic function a Calculation applies.
type Operation string

// PercentageCalculation Percent-of — what share of `of` the `percent` percentage represents.
type PercentageCalculation struct {
	// Of An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Of        Operand                        `json:"of"`
	Operation PercentageCalculationOperation `json:"operation"`

	// Percent An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Percent Operand `json:"percent"`
}

// PercentageCalculationOperation defines model for PercentageCalculation.Operation.
type PercentageCalculationOperation string

// UnaryCalculation An Operation over the single Operand `operand`.
type UnaryCalculation struct {
	// Operand An input value to a Calculation, carried as a decimal string. Exponent notation is deliberately rejected: one input form, one parser. A magnitude cap on exponents is not expressible here and is enforced in the domain, surfacing as 422 `result_too_large`.
	//
	// Example: 0.1
	Operand   Operand                   `json:"operand"`
	Operation UnaryCalculationOperation `json:"operation"`
}

// UnaryCalculationOperation defines model for UnaryCalculation.Operation.
type UnaryCalculationOperation string

// SessionId defines model for SessionId.
type SessionId = openapi_types.UUID

// GetCalculationsParams defines parameters for GetCalculations.
type GetCalculationsParams struct {
	// XSessionId The Session whose History this request reads or appends to. It carries no identity beyond separating one caller's History from another's.
	XSessionId SessionId `json:"X-Session-Id"`
}

// PostCalculationsParams defines parameters for PostCalculations.
type PostCalculationsParams struct {
	// XSessionId The Session whose History this request reads or appends to. It carries no identity beyond separating one caller's History from another's.
	XSessionId SessionId `json:"X-Session-Id"`
}

// PostCalculationsJSONRequestBody defines body for PostCalculations for application/json ContentType.
type PostCalculationsJSONRequestBody = CalculationRequest

// AsBinaryCalculation returns the union data inside the CalculationRequest as a BinaryCalculation
func (t CalculationRequest) AsBinaryCalculation() (BinaryCalculation, error) {
	var body BinaryCalculation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBinaryCalculation overwrites any union data inside the CalculationRequest as the provided BinaryCalculation
func (t *CalculationRequest) FromBinaryCalculation(v BinaryCalculation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBinaryCalculation performs a merge with any union data inside the CalculationRequest, using the provided BinaryCalculation
func (t *CalculationRequest) MergeBinaryCalculation(v BinaryCalculation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUnaryCalculation returns the union data inside the CalculationRequest as a UnaryCalculation
func (t CalculationRequest) AsUnaryCalculation() (UnaryCalculation, error) {
	var body UnaryCalculation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUnaryCalculation overwrites any union data inside the CalculationRequest as the provided UnaryCalculation
func (t *CalculationRequest) FromUnaryCalculation(v UnaryCalculation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUnaryCalculation performs a merge with any union data inside the CalculationRequest, using the provided UnaryCalculation
func (t *CalculationRequest) MergeUnaryCalculation(v UnaryCalculation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPercentageCalculation returns the union data inside the CalculationRequest as a PercentageCalculation
func (t CalculationRequest) AsPercentageCalculation() (PercentageCalculation, error) {
	var body PercentageCalculation
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPercentageCalculation overwrites any union data inside the CalculationRequest as the provided PercentageCalculation
func (t *CalculationRequest) FromPercentageCalculation(v PercentageCalculation) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePercentageCalculation performs a merge with any union data inside the CalculationRequest, using the provided PercentageCalculation
func (t *CalculationRequest) MergePercentageCalculation(v PercentageCalculation) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CalculationRequest) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"operation"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t CalculationRequest) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "add":
		return t.AsBinaryCalculation()
	case "divide":
		return t.AsBinaryCalculation()
	case "multiply":
		return t.AsBinaryCalculation()
	case "percentage":
		return t.AsPercentageCalculation()
	case "power":
		return t.AsBinaryCalculation()
	case "sqrt":
		return t.AsUnaryCalculation()
	case "subtract":
		return t.AsBinaryCalculation()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t CalculationRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CalculationRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetCalculations Read the Session's History
	// (GET /calculations)
	GetCalculations(w http.ResponseWriter, r *http.Request, params GetCalculationsParams)
	// PostCalculations Perform a Calculation
	// (POST /calculations)
	PostCalculations(w http.ResponseWriter, r *http.Request, params PostCalculationsParams)
	// GetHealth Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCalculations operation middleware
func (siw *ServerInterfaceWrapper) GetCalculations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCalculationsParams

	headers := r.Header

	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Session-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Session-Id", Err: err})
			return
		}

		params.XSessionId = XSessionId

	} else {
		err := fmt.Errorf("Header parameter X-Session-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Session-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCalculations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCalculations operation middleware
func (siw *ServerInterfaceWrapper) PostCalculations(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostCalculationsParams

	headers := r.Header

	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Session-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Session-Id", Err: err})
			return
		}

		params.XSessionId = XSessionId

	} else {
		err := fmt.Errorf("Header parameter X-Session-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Session-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCalculations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/calculations", wrapper.GetCalculations)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/calculations", wrapper.PostCalculations)

	return m
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFn/bts4En6VAW+B3cUpTjbb/cf/LLKLxTbA3SXoj7sD2lw0FkcWW4lkSSq2Wxi4h7gnvCc5DCnZsq0k",
	"9W1b9C9XCinOfPzmm4/sB1GYxhpNOngx/SAsOmwokItPz8l7ZfSl5AdJvnDKBmW0mIoXFUH3Z1hUxhM8",
	"VT4Yt4JQKQ+O3rXkAzhC6cE4QGtJSw/BTOAyQIHOKfKgDShJOqiwghmtjJbgiYMISs/BaIIC65rct37z",
	"/dKZBlCbUPHriciE4oAqQklOZEJjQ2Iq/nnShXdyKUUmOCDlSIppcC1lwhcVNch5lcY1GMRUtK3ikWFl",
	"eb4PTum5WK/X/eAIyS9Ko1v9inXR1piw+CBQSsX/xvraGUsuKPJiWmLtKdvD7ULDlSUXp4K5IwehovSK",
	"4clrKkMOqCXkTs2rkHOCdvDVD4KH8O83jkoxFX863W7haRfpafdBsc6E6ZfjOaTbRkxfccQiE76dBYdF",
	"EJlo2jooW69EJqS6U5J4WbMgJ24OIMlEDO2jY1gP4X81CChLufTf265kZm+oCLzSHtK7YF5pGqCJ1taK",
	"JAQDKvgNphksVKgizM/It3UAFcA6I9uC5AReDOG3jjzpAOgoTjCa/HaDeJVvPaBjtjLN/GRTAxsWKyZ1",
	"AIsugCkBYZDB4V7SkuE/SOwfFTG9h0H3FcOpMYWhwcA4B1VgDXdYt5QS1QakmvMwqXyBTnKWF/UCV1yW",
	"1rhAMgNNzD2lS3KO5GTL+5kxNaFm7I8lWnksK7X8f3n86Jw4cJ0JS64gfUwaLuI9rng9gXTcBl8xmD4A",
	"SwiECkMPud/uAkNLS2xszeieTX4Un7OeuuCzjliPVNSzpNKHuV4MWcsFZclxkqlc7tAp1IGp7qmmIpCE",
	"2QryTSB5Bt4ADqWuQA1G16zyEEtsU5Sb4mNIU21hXZtFRI7xdKpRGoNxHGeD1jJoSXXvg+pQpTeydsSM",
	"jSYeMafjG87vXel6M2JvZlTbI5by71y4b/zLkeG92H/0EuuNWq3+lpqqGZaW0XRViumrh1k79tmHZ7w8",
	"dsI4ouubdSZ+cy7xZk92+9cPfTbO/dVI4mQb8j5u6n6pPG0b1Cfsc3BWE9DS1qhjBBk40pJcfM90N20A",
	"hMJIOgnmpDB2BQ3aXYFglsaGMlvBe3JmxJDsVn9KZRvgWMlvMzkI/69YVErTIAEeG4OMgXV+Qek7rJW8",
	"7XxdV04c6O1sddsF2mpJpdLEwzoZ0jTHoO7o1r9r0dGtMyZsZOo2GHNbo5tTNHGBnMb6NiU05jqeEtah",
	"OtxNHzC0fTvtcDRvH0WumzYGWOc1x5vAgGQecOMAKvS9TKYGu4itQTkfokkN1PjHKLdXfV1c6Byu+Plq",
	"2zQPXKXStg2dDwhm13dknXuQgByxpEI1WEPCZQK/LVMcbFySWisPkmo142qnegWO3kSZn0ZLnpbiRLP4",
	"bNF5chO4gAbnWoVWsm23YDSXQ0qx90W0ZI/lFVOtIkfR6ioPpEvjCpLcW7krSNOg0hn41pVY8GEAPTw5",
	"P4d8nzv5fof9gasBl38hPWe2/HSWCYuB2SWm4l8nP79+Lf/83evXE/79/udvxvrx1dBrHDKAvZ+Mvapq",
	"KKgCylYXyYPuNM7kSP2wkI4w3p3C7/SUsbIYl7/jjiXdN05MCf/9939gwV7GV2yDTQm5KfO4KXkXSQ7b",
	"kNhTJtfsD+3t8ZZw/6DySO7H2rsHrFP/qWhkx0Th5ec4+Xml5/XGBHUeSsuRY98fdMw9oJFTN49p4xCY",
	"fuFDTHiW0qU5rJLnKS1vWldEDgXXhoo1I2Z9cX2Z6BWNI7/53cAMi7ekZVSEdPDBIvBxXwfSkmWKf9P9",
	"grdUJG3NeKwGR3PSUa5gZkIFXknyyWTmVtsG+j9HZIMKUSye0/v3NcELfEsnT00TAxOZuCPnUx4/TM4m",
	"Zx2WGq0SU/HjJJl4i6GKG3NaDBoCv5hT+IjOEfP4yOax2Y5Ltry/Uxh+Kcayvba5x49th5xur3XWN7EX",
	"W6N9Itn52Rn/FBHzmEXUsCKudPrGJy5tL08eYmLfRCNN7r092t7s7Ke9zsSTTxhOsoL3BNPfVykPDdZp",
	"G6IS5nvOJ49x/fQl4nqpaWnT6apEVbeO+oiGTokDWnNHaRpkxyKeEab6OQA4CqYZPe+lRhW7+Vak9i5S",
	"YmE6Kgyfb8Munfu2fbDmIXuvjf+09I378ouRq0+2JSNH5PWuQgbX0voz1s6OERyn7BD9BXog9n4YSH7V",
	"lfPk/PzLxsXQ8MHE+WCMhFkbDrjL4qtNdzkWD0HdPU9MY/+gk2eQ7590+N3YUSfPwLhRy/qVi8h16kW7",
	"fjaOOa02p7DRPvcsouhhMbjC5HavPLR2tJd1x7rP2YnSCvcwZRDdl9qVnWUjJ1udcF3t70SKHYqKirfd",
	"/0aQu+ul8vCzvV8CR1hU3fV1b61iIcQ3p2gVWEelWsJ3f1eBwDqzXH3PO9S6WkwFjxDrm/X/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
