root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/server ./cmd/server"
entrypoint = "./tmp/server"
include_ext = ["go"]
exclude_dir = ["tmp", "bin"]
delay = 200

[log]
main_only = true

[misc]
clean_on_exit = true
